### ISSUE TITLE
Cannot subscribe to subreddit

### ISSUE THREAD

**Issue by ReenigneArcher** [RedditBot-Discord/redditbot#30] opened 2021-05-04 13:56 UTC
I checked the `/help` before creating this issue. https://docs.redditbot.bwac.dev/get-info/subscriptions

The `/subscriptions subscribe` command is no longer available.

![image](https://user-images.githubusercontent.com/42013603/117014354-b7a8f880-acbe-11eb-9047-0624a493ed1a.png)

![image](https://user-images.githubusercontent.com/42013603/117014427-c8596e80-acbe-11eb-883d-edb833ca6555.png)

I am the server owner, so not sure why it is not appearing today. It was available yesterday.

**Comment by ReenigneArcher** [comment] 2021-05-04 22:21
Might be related but `/subreddit` command is also failing.

![image](https://user-images.githubusercontent.com/42013603/117077138-91f31200-ad05-11eb-9588-3a768e1e595d.png)

**Comment by bwac2517** [comment] 2021-05-04 22:25
Ah, thanks! I'll have a look at the logs when I can next.

The docs are outdated right now and I need to fix them yes.

The second `/subreddit` issue is caused by Google cloud run cold starts, it should be fixed by simply trying again. It happens sometimes.

**Comment by bwac2517** [comment] 2021-05-04 22:29
`/subscriptions subscribe` was replaced with `/subscriptions live`. You may need to reinvite the bot for new commands to show. (readding the bot won't affect your subscriptions.)

**Comment by bwac2517** [comment] 2021-05-04 22:32
> The second `/subreddit` issue is caused by Google cloud run cold starts, it should be fixed by simply trying again. It happens sometimes.
This is an issue I have no idea how to fix and it's super annoying

**Comment by ReenigneArcher** [comment] 2021-05-04 22:43
Okay thanks for clarifying. I thought the `/subscriptions live` command was to show only "Live chat discussion" type of posts from a subreddit. That is a little bit confusing.

The second issue worked on my second attempt. Not familiar enough with google cloud to help on that. I have a possible workaround though... Does RedditBot know the interaction failed before sending the message to the discord channel? I assume yes... and if so could you have the RedditBot automatically try again?

**Comment by bwac2517** [comment] 2021-05-05 04:42
I think its discord assuming it failed before it even gave redditbot a chance to respond.

Anyway, im glad i could help.

**Closed by bwac2517** 2021-05-05 04:42 UTC
